services:
  db:
    image: docker.arvancloud.ir/postgres:14.1
    container_name: db_api
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d db"]
      interval: 5s
      timeout: 5s
      retries: 5


  django:
    build:
      context: .
      dockerfile: docker/stage.Dockerfile
    entrypoint: /entrypoint.sh
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./core/:/app
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  celery:
    build:
      context: .
      dockerfile: docker/stage.Dockerfile
    command: celery -A core worker --loglevel=info
    volumes:
      - ./core/:/app
    depends_on:
      - redis
    restart: on-failure


  redis:
    image: docker.arvancloud.ir/redis
    container_name: redis-celery
    ports:
      - 6379:6379

