# Generated by Django 5.0.2 on 2024-04-24 02:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customerprofile_driverprofile'),
        ('trips', '0002_city_driveroffers_trips_driver_offers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.customerprofile')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.driverprofile')),
                ('trips', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trips.trips')),
            ],
        ),
    ]
