# Generated by Django 5.0.2 on 2024-05-07 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_alter_driveroffers_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driveroffers',
            name='end_key',
            field=models.CharField(default=12, max_length=120),
            preserve_default=False,
        ),
    ]
