# Generated by Django 5.0.2 on 2024-05-08 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_driveroffers_end_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='trips',
            new_name='trip',
        ),
    ]
