# Generated by Django 5.0.2 on 2024-05-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_rename_trips_comment_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_show',
            field=models.BooleanField(default=False),
        ),
    ]
