# Generated by Django 5.0.2 on 2024-05-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_comment_is_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
