# Generated by Django 5.0.2 on 2024-05-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_photo_driverprofile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='image',
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='ID_image',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
