# Generated by Django 5.0.2 on 2024-05-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_car_image_driverprofile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
