name: CD for bitaxi
on:
    pull_request:
      branches:
        - main
  
jobs:
    quality-assurance:
      name: check CI before deploy 
      uses: ./.github/workflows/ci.yml

    simple_CD:
      name: Django CD
      needs:
        - quality-assurance
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Connect and Execute Commands
        uses: appleboy/ssh-action@master
        with:
          username: ${{secrets.SSH_USER}}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{secrets.SSH_HOST}}
          script: |
            cd bitaxi
            docker compose -f docker-compose-dev.yaml down
            git pull
            docker compose -f docker-compose-dev.yaml build
            docker compose -f docker-compose-dev.yaml up -d --force-recreate