name: CD for bitaxi
on:
    push:
      branches:
        - main
  
jobs:
    simple_CD:
      name: Django CD
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Connect and Execute Commands
        uses: appleboy/ssh-action@master
        with:
          username: ${{secrets.SSH_USER}}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{secrets.SSH_HOST}}
          script: |
            cd bitaxi
            docker compose -f docker-compose-prod.yaml down
            git pull
            docker compose -f docker-compose-prod.yaml build
            docker compose -f docker-compose-prod.yaml up -d --force-recreate